/* tslint:disable */
/* eslint-disable */
/**
 * TODO API
 * Application Interface Definition
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface BacklogResponse
 */
export interface BacklogResponse {
  /**
   *
   * @type {number}
   * @memberof BacklogResponse
   */
  id: number;
  /**
   * カラムタイトル
   * @type {string}
   * @memberof BacklogResponse
   */
  title: string;
  /**
   * カラムの説明
   * @type {string}
   * @memberof BacklogResponse
   */
  description?: string;
  /**
   * カラムの並び順
   * @type {number}
   * @memberof BacklogResponse
   */
  position: number;
}

/**
 * Check if a given object implements the BacklogResponse interface.
 */
export function instanceOfBacklogResponse(
  value: object,
): value is BacklogResponse {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("title" in value) || value["title"] === undefined) return false;
  if (!("position" in value) || value["position"] === undefined) return false;
  return true;
}

export function BacklogResponseFromJSON(json: any): BacklogResponse {
  return BacklogResponseFromJSONTyped(json, false);
}

export function BacklogResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): BacklogResponse {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    title: json["title"],
    description: json["description"] == null ? undefined : json["description"],
    position: json["position"],
  };
}

export function BacklogResponseToJSON(json: any): BacklogResponse {
  return BacklogResponseToJSONTyped(json, false);
}

export function BacklogResponseToJSONTyped(
  value?: BacklogResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    title: value["title"],
    description: value["description"],
    position: value["position"],
  };
}
