/* tslint:disable */
/* eslint-disable */
/**
 * TODO API
 * Application Interface Definition
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface InternalServerError
 */
export interface InternalServerError {
  /**
   * HTTP status code
   * @type {number}
   * @memberof InternalServerError
   */
  statusCode: number;
  /**
   * Error message
   * @type {string}
   * @memberof InternalServerError
   */
  message: string;
}

/**
 * Check if a given object implements the InternalServerError interface.
 */
export function instanceOfInternalServerError(
  value: object,
): value is InternalServerError {
  if (!("statusCode" in value) || value["statusCode"] === undefined)
    return false;
  if (!("message" in value) || value["message"] === undefined) return false;
  return true;
}

export function InternalServerErrorFromJSON(json: any): InternalServerError {
  return InternalServerErrorFromJSONTyped(json, false);
}

export function InternalServerErrorFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): InternalServerError {
  if (json == null) {
    return json;
  }
  return {
    statusCode: json["statusCode"],
    message: json["message"],
  };
}

export function InternalServerErrorToJSON(json: any): InternalServerError {
  return InternalServerErrorToJSONTyped(json, false);
}

export function InternalServerErrorToJSONTyped(
  value?: InternalServerError | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    statusCode: value["statusCode"],
    message: value["message"],
  };
}
